services:
  - type: web
    runtime: node
    name: baqala
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: PORT
        value: 10000
